language: go

go: 1.6

before_install:
- sudo apt-get update
- sudo apt-get install npm
- npm install -g gulp bower

install:
- go get -d -v ./...
- go build -v ./...
- pushd client
- npm install
- bower install
- gulp
- popd

script: ./test.sh
