language: go

go: 1.6

before_install:
- sudo apt-get update
- sudo apt-get install npm
- npm install -g gulp bower

install:
# Compile the server
- go get -d -v ./...
- go build -v ./...
# Build the client
- pushd client
- npm install
- bower install
- gulp
- popd

script: ./test.sh
